name: CI Docker Build and Run

on:
  push:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generar un identificador basado en el commit
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Construir la imagen Docker con tag único
        run: | 
          docker build -t ${{ vars.ACR_CLOUD }}/my-python-app:$IMAGE_TAG .     

      - name: Ejecutar el contenedor y probar el script
        run: |
          docker run --rm ${{ vars.ACR_CLOUD }}/my-python-app:$IMAGE_TAG
  
      - name: Login to Azure for ACR
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_ACR_CREDENTIALS }}
 
      - name: Login to ACR
        run: |
          az acr login --name ${{ vars.ACR_CLOUD }}

      - name: Publicar la imagen Docker con tag único
        run: | 
          docker push ${{ vars.ACR_CLOUD }}/my-python-app:$IMAGE_TAG
